### ISSUE TITLE
React 17 - Error: Invalid hook call

### ISSUE THREAD

**Issue by srameshr** [hipstersmoothie/react-glider#79]
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.



 at resolveDispatcher (/Users/username/Desktop/code/apps/app/app.app/node_modules/react-glider/node_modules/react/cjs/react.development.js:1465:13)
    at Object.useRef (/Users/username/Desktop/code/apps/app/app.app/node_modules/react-glider/node_modules/react/cjs/react.development.js:1504:20)
    at Object.render (/Users/username/Desktop/code/apps/app/app.app/node_modules/react-glider/dist/index.js:38:26)
    at ReactDOMServerRenderer.render (/Users/username/Desktop/code/apps/app/app.app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3872:44)
    at ReactDOMServerRenderer.read (/Users/username/Desktop/code/apps/app/app.app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/Users/username/Desktop/code/apps/app/app.app/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/Users/username/Desktop/code/apps/app/app.app/node_modules/next/dist/next-server/server/render.js:54:854)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:211:19)
    at loadGetInitialProps (/Users/username/Desktop/code/apps/app/app.app/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/Users/username/Desktop/code/apps/app/app.app/node_modules/next/dist/next-server/server/render.js:54:1145)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/username/Desktop/code/apps/app/app.app/node_modules/next/dist/next-server/server/next-server.js:112:97
    at async __wrapper (/Users/username/Desktop/code/apps/app/app.app/node_modules/next/dist/lib/coalesced-function.js:1:330)
    at async DevServer.renderToHTMLWithComponents (/Users/username/Desktop/code/apps/app/app.app/node_modules/next/dist/next-server/server/next-server.js:137:387)
    at async DevServer.renderToHTML (/Users/username/Desktop/code/apps/app/app.app/node_modules/next/dist/next-server/server/next-server.js:138:1088)
```

**Comment by srameshr** [comment]
Its with the React version mismatch in @reach/auto-id and this package. If I got to node_moduels/react-glider folder and delete the react and react-dom package it works just fine.

**Comment by srameshr** [comment]
I figured it out. It has because @reach/auto-id has a mismatch version with this lib after the latest update.

**Comment by joaovictor3g** [comment]
hi @srameshr  i would like to solve this problem, could you assign me?

**Comment by srameshr** [comment]
You can pick it up @joaovictor3g

**Comment by hamedov93** [comment]
Any update on this issue ?

**Comment by kevinfarrugia** [comment]
@hamedov93 can you please include a minimal, reproducible example?

**Comment by kevinfarrugia** [comment]
I created a PR for this but was unable to reproduce the error.

https://github.com/hipstersmoothie/react-glider/pull/83
