### ISSUE TITLE
Storybook fails on Node 17

### ISSUE THREAD

**Issue by kevinfarrugia** [hipstersmoothie/react-glider#92]
Storybook is failing when building using Node 17 and upwards.

**Console output:**
```
$ yarn storybook
yarn run v1.22.5
$ start-storybook -p 9001 -c .storybook
info @storybook/react v5.3.21
info 
info => Loading presets
info => Loading presets
info => Loading custom manager config.
info => Loading config/preview file in ".storybook".
info => Loading custom Webpack config (full-control mode).
info => Using base config because react-scripts is not installed.
10% building 1/1 modules 0 active(node:166735) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(Use `node --trace-deprecation ...` to show where the warning was created)
10% building 1/2 modules 1 active /home/kevin/git/react-glider/node_modules/webpack-hot-middleware/client.js?reload=true&quiet=truenode:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/kevin/git/react-glider/node_modules/@storybook/core/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/kevin/git/react-glider/node_modules/@storybook/core/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/kevin/git/react-glider/node_modules/@storybook/core/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/kevin/git/react-glider/node_modules/@storybook/core/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/kevin/git/react-glider/node_modules/@storybook/core/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/kevin/git/react-glider/node_modules/@storybook/core/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/kevin/git/react-glider/node_modules/@storybook/core/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/kevin/git/react-glider/node_modules/@storybook/core/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/kevin/git/react-glider/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at /home/kevin/git/react-glider/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9
    at /home/kevin/git/react-glider/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.2.0
```

**Comment by kevinfarrugia** [comment]
Mitigated by using `cimg/node:lts` CircleCI docker image.
